version: 2
jobs:
  hello:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "It's working!"
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Wait for prerequisite to run, then will run 'npm test'"
      - run: npm install
      - run: npm test
  prerequisite:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Meaningless job, but proves a point."
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - hello
      - build
      - prerequisite
      - test:
          requires:
            - prerequisite

